version: "3"
services:
  client:
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile
    image: morais/farmers-market-client:latest
    environment:
      MARKET_SERVICE_HOST: http://market-api:${MARKET_GATEWAY_PORT}
    depends_on:
      - market-api
      - products-seed
      - specials-seed
  client-tests:
    image: "morais/farmers-market-client:latest"
    command: ["python", "-m", "pytest"]
    environment:
      MARKET_SERVICE_HOST: http://market-api:${MARKET_GATEWAY_PORT}
    depends_on:
      - market-api
      - products-seed
      - specials-seed
  market-api:
    build:
      context: ./
      dockerfile: ./docker/gateway/Dockerfile
    image: morais/farmers-market-api:latest
    environment:
      MARKET_GATEWAY_PORT: "${MARKET_GATEWAY_PORT}"
      CART_SERVICE_HOST: http://carts:${MARKET_CARTS_PORT}
      PRODUCT_SERVICE_HOST: http://products:${MARKET_PRODUCTS_PORT}
      CASHIER_SERVICE_HOST: http://cashier:${MARKET_CASHIER_PORT}
    depends_on:
      - products
      - carts
      - cashier
  market-api-tests:
    image: "morais/farmers-market-api:latest"
    command: ["python", "-m", "pytest"]
    environment:
      CART_SERVICE_HOST: http://carts:${MARKET_CARTS_PORT}
      PRODUCT_SERVICE_HOST: http://products:${MARKET_PRODUCTS_PORT}
      CASHIER_SERVICE_HOST: http://cashier:${MARKET_CASHIER_PORT}
    depends_on:
      - products
      - carts
      - cashier
  products:
    build:
      context: ./
      dockerfile: ./docker/products/Dockerfile
    image: morais/farmers-market-products:latest
    environment:
      MARKET_PRODUCTS_PORT: ${MARKET_PRODUCTS_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PRODUCT_DB_HOST: productdb
    depends_on:
      - productdb
  products-tests:
    image: "morais/farmers-market-products:latest"
    command: ["python", "-m", "pytest"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PRODUCT_DB_HOST: productdb
    depends_on:
      - productdb
  products-seed:
    image: "morais/farmers-market-products:latest"
    command: ["python", "seed.py"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PRODUCT_DB_HOST: productdb
    depends_on:
      - productdb
  productdb:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "market"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword", "--silent"]
      interval: 5s
    ports:
      - 3306:3306
    volumes:
      - db-data:/data/db
  carts:
    build:
      context: ./
      dockerfile: ./docker/carts/Dockerfile
    image: morais/farmers-market-carts:latest
    environment:
      MARKET_CARTS_PORT: "${MARKET_CARTS_PORT}"
      CART_STORE_HOST: cart-store
      CASHIER_SERVICE_HOST: http://cashier:${MARKET_CASHIER_PORT}
    depends_on:
      - cart-store
      - cashier
  carts-tests:
    image: "morais/farmers-market-carts:latest"
    command: ["python", "-m", "pytest"]
    environment:
      MARKET_CARTS_PORT: ${MARKET_CARTS_PORT}
      CART_STORE_HOST: cart-store
      PRODUCT_SERVICE_HOST: http://products:${MARKET_PRODUCTS_PORT}
      CASHIER_SERVICE_HOST: http://cashier:${MARKET_CASHIER_PORT}
    depends_on:
      - products-seed
      - cart-store
      - cashier
  cart-store:
    image: "redis:alpine"
  cashier:
    build:
      context: ./
      dockerfile: ./docker/cashier/Dockerfile
    image: morais/farmers-market-cashier:latest
    environment:
      DOC_STORE_HOST: doc-store
      PRODUCT_SERVICE_HOST: http://products:${MARKET_PRODUCTS_PORT}
      MARKET_CASHIER_PORT: "${MARKET_CASHIER_PORT}"
    depends_on:
      - doc-store
      - products
  cashier-tests:
    image: "morais/farmers-market-cashier:latest"
    command: ["python", "-m", "pytest"]
    environment:
      DOC_STORE_HOST: doc-store
      PRODUCT_SERVICE_HOST: http://products:${MARKET_PRODUCTS_PORT}
    depends_on:
      - products-seed
      - specials-seed
      - doc-store
      - products
  specials-seed:
    image: "morais/farmers-market-cashier:latest"
    command: ["python", "seed.py"]
    environment:
      DOC_STORE_HOST: doc-store
    depends_on:
      - doc-store
  doc-store:
    image: mongo:latest
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_DATABASE: market
      MONGODB_PASS: ${MONGODB_PASS}
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - doc-data:/data/db
    ports:
      - 32001:27017

volumes:
  db-data:
  doc-data:

