version: "3"
services:
  client:
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile
    image: morais/farmers-market-client:latest
    environment:
      MARKET_SERVICE_HOST: market-api
    depends_on:
      - market-api
      - products-seed
  client-tests:
    image: "morais/farmers-market-client:latest"
    command: python -m pytest
    depends_on:
      - market-api
      - products-seed
  market-api:
    build:
      context: ./
      dockerfile: ./docker/gateway/Dockerfile
    image: morais/farmers-market-api:latest
    environment:
      MARKET_PRODUCTS_HOST: products 
      MARKET_CARTS_HOST: carts
      MARKET_SPECIALS_HOST: specials
    depends_on:
      - products
      - carts
      - specials
  market-api-tests:
    image: "morais/farmers-market-api:latest"
    command: python -m pytest
    depends_on:
      - products
      - carts
      - specials
  products:
    build:
      context: ./
      dockerfile: ./docker/products/Dockerfile
    image: morais/farmers-market-products:latest
    environment:
      PRODUCT_DB_HOST: productdb
    depends_on:
      - productdb
  products-tests:
    image: "morais/farmers-market-products:latest"
    command: python -m pytest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PRODUCT_DB_HOST: productdb
    depends_on:
      - productdb
  products-seed:
    image: "morais/farmers-market-products:latest"
    command: python seed.py
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PRODUCT_DB_HOST: productdb
    depends_on:
      - productdb
  productdb:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "market"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword", "--silent"]
      interval: 5s
    ports:
      - 3306:3306
    volumes:
      - db-data:/data/db
  carts:
    build:
      context: ./
      dockerfile: ./docker/carts/Dockerfile
    image: morais/farmers-market-carts:latest
    environment:
      CART_STORE_HOST: store
      CART_STORE_PORT: 
    links:
      - cartstore:store
    depends_on:
      - cartstore
  carts-tests:
    image: "morais/farmers-market-carts:latest"
    command: python -m pytest
    links:
      - cartstore:store
    depends_on:
      - cartstore
  cartstore:
    image: "redis:alpine"
  specials:
    build:
      context: ./
      dockerfile: ./docker/specials/Dockerfile
    image: morais/farmers-market-specials:latest
    depends_on:
      - docstore
  specials-tests:
    image: "morais/farmers-market-specials:latest"
    command: python -m pytest
    links:
      - docstore:store
    depends_on:
      - docstore
  docstore:
    image: mongo:latest
    environment:
      MONGODB_USER: "${MONGODB_USER}"
      MONGODB_DATABASE: "${SPECIALS_STORE}"
      MONGODB_PASS: "${MONGODB_PASS}"
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - doc-data:/data/db
    ports:
      - 32001:27017

volumes:
  db-data:
  doc-data:

