version: "3"
services:
  client:
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile
    image: morais/farmers-market-client:latest
    environment:
      MARKET_SERVICE_HOST: api
      MARKET_SERVICE_PORT: "${MARKET_GATEWAY_PORT}"
    links:
      - market-api:api 
    depends_on:
      - market-api
  client-tests:
    image: "morais/farmers-market-client:latest"
    command: python -m pytest
  market-api:
    build:
      context: ./
      dockerfile: ./docker/gateway/Dockerfile
    image: morais/farmers-market-api:latest
    environment:
      MARKET_PRODUCTS_HOST: products 
      MARKET_PRODUCTS_PORT: "${MARKET_PRODUCTS_PORT}"
      MARKET_CARTS_HOST: carts
      MARKET_CARTS_PORT: "${MARKET_CARTS_PORT}"
      MARKET_SPECIALS_HOST: specials
      MARKET_SPECIALS_PORT: "${MARKET_SPECIALS_PORT}"
    links:
      - products:products
      - carts:carts
      - specials:specials
    depends_on:
      - products
      - carts
      - specials
  market-api-tests:
    image: "morais/farmers-market-api:latest"
    command: python -m pytest
  products:
    build:
      context: ./
      dockerfile: ./docker/products/Dockerfile
    image: morais/farmers-market-products:latest
    environment:
      PRODUCT_DB_HOST: db
      PRODUCT_DB_PORT: 3306
    links:
      - productdb:db
    depends_on:
      - productdb
  products-tests:
    image: "morais/farmers-market-products:latest"
    command: python -m pytest
    environment:
      PRODUCT_DB_HOST: db
      PRODUCT_DB_PORT: 3306
    links:
      - productdb:db
    depends_on:
      - productdb
  productdb:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "market"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword", "--silent"]
      interval: 5s
    ports:
      - 3306:3306
    volumes:
      - db-data:/data/db
  carts:
    build:
      context: ./
      dockerfile: ./docker/carts/Dockerfile
    image: morais/farmers-market-carts:latest
    environment:
      CART_STORE_HOST: store
      CART_STORE_PORT: 
    links:
      - cartstore:store
    depends_on:
      - cartstore
  carts-tests:
    image: "morais/farmers-market-carts:latest"
    command: python -m pytest
    links:
      - cartstore:store
    depends_on:
      - cartstore
  cartstore:
    image: "redis:alpine"
  specials:
    build:
      context: ./
      dockerfile: ./docker/specials/Dockerfile
    image: morais/farmers-market-specials:latest
    depends_on:
      - docstore
  specials-tests:
    image: "morais/farmers-market-specials:latest"
    command: python -m pytest
    links:
      - docstore:store
    depends_on:
      - docstore
  docstore:
    image: mongo:latest
    environment:
      MONGODB_USER: "${MONGODB_USER}"
      MONGODB_DATABASE: "${SPECIALS_STORE}"
      MONGODB_PASS: "${MONGODB_PASS}"
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - doc-data:/data/db
    ports:
      - 27017:27017

volumes:
  db-data:
  doc-data:

